### ISSUE TITLE
[UwpList] packageName always empty

### ISSUE THREAD

**Issue by sirotnikov** [zodiacon/WindowsInternals#10]
Hi!

when getting the package name in **DisplayProcessInfo**
after `auto error = ::GetPackageFullName(...);`
1. should check `error == ERROR_INSUFFICIENT_BUFFER` instead of `ERROR_SUCCESS`
2. the `name` unique_ptr should be declared _before_ the `if` scope, or else it goes out of scope, and `packageName` will be a dangling pointer

**Comment by zodiacon** [comment]
Good catch!
Fixed
