### ISSUE TITLE
Windows Kernel Error

### ISSUE THREAD

**Issue by zer0cat** [zodiacon/WindowsInternals#17]
Hello,
I writing simple driver for your book, and have error with

`DriverObject->MajorFunction[IRP_MJ_CREATE] = PriorityBoosterCreateClose;`

Visual Studio2019 says, that NTSTATUS no equal PDRIVER_DISPATCH

Why? 

I write
`DriverObject->MajorFunction[IRP_MJ_CREATE] = (PDRIVER_DISPATCH)PriorityBoosterCreateClose;`

But is it right way?

**Comment by zodiacon** [comment]
The cast is not needed, you must make sure your function is declared with the required prototype:
NTSTATUS PriorityBoosterCreateClose(PDEVICE_OBJECT, PIRP);

**Comment by zer0cat** [comment]
Sorry. I wrote _PDRIVER_OBJECT_ instead of _PDEVICE_OBJECT_. I am stupid.
Thank you for the answer and for the book!
