### ISSUE TITLE
UwpList - BuildCapabilityMap parser bug

### ISSUE THREAD

**Issue by dmex** [zodiacon/WindowsInternals#2]
Hello,

The BuildCapabilityMap function in the UwpList project fails to parse the caps.txt file.

The .gitattributes file for this repository specifies "text=auto" and Github defaults to LF (\n) line endings for text files - this causes the BuildCapabilityMap function to fail parsing the caps.txt file since the line endings were changed from CRLF (\r\n) to LF (\n) when the code was committed.

You will need to change the BuildCapabilityMap function, line 150 from: 
auto cr = ::strstr(caps, "\r\n");
To: 
auto cr = ::strstr(caps, "\n");

And line 168 from:
caps = cr + 2;
To:
caps = cr + 1;

Otherwise anyone downloading the UwpList project won't be able to use it properly. 

Since these are all Windows based tools and files, I highly suggest changing the .gitattributes file to use "text=crlf" and just re-commit the code to save time and prevent future issues.

**Comment by zodiacon** [comment]
Good catch. Why don't you submit a pull request? :)

**Comment by dmex** [comment]
Thanks for merging the patch, I'll close the ticket 👍
