### ISSUE TITLE
ctrl2cap

### ISSUE THREAD

**Issue by aagarwal584** [zodiacon/WindowsInternals#5]
Hi zodiacon,
Please see a question regarding wininternal tool, specifically ctrl2cap.  Is there a way to modify the tool to convert "~" to another character.  Default behavior is to convert "CAPS LOCK" to "Left CONTROL"?
Thanks.
Regards,
aagarwal584

**Comment by zodiacon** [comment]
This tool was written by Mark Russinovich... any question about it should go to him.

**Comment by aagarwal584** [comment]
Thanks for the prompt answer!  Are you aware of any contact info for Mark Russinovich.

**Comment by zodiacon** [comment]
You can try the Sysinternals forum or his email markruss@microsoft.com

**Comment by aagarwal584** [comment]
Many thanks for the pointer!
